spring.application.name=gestion-clinique-api

spring.datasource.url=jdbc:postgresql://localhost:5432/cliniquedb?user=chijou&password=duro@chijou
spring.datasource.username=chijou
spring.datasource.password=duro@chijou
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
